package entity

/** All 23 OSRS skills. Source: https://oldschool.runescape.wiki/w/Skills */
enum class Skill {
    ATTACK, DEFENCE, STRENGTH, HITPOINTS, RANGED, PRAYER, MAGIC,
    COOKING, WOODCUTTING, FLETCHING, FISHING, FIREMAKING, CRAFTING,
    SMITHING, MINING, HERBLORE, AGILITY, THIEVING, SLAYER, FARMING,
    RUNECRAFT, HUNTER, CONSTRUCTION
}
